### ISSUE TITLE
Review Wiki 

### ISSUE THREAD

**Issue by FuratH** [pp-team2/Kopfsachen-react-bootstrap#1]

**Comment by Leonhardt2** [comment]
Die Links zu den einzelnen Wikientries in der WikiList habe ich von einem li-Element zu einem Bootstrap-Button geändert, damit der Browser den Link erkennt und es besser aussieht.  Das Inline-CSS ist nicht unbedingt optimal und bietet noch Verbesserungsbedarf.

**Comment by Siar-Akbayin** [comment]
Sieht gut aus, aber die Bilder laden nicht:


![Image](https://user-images.githubusercontent.com/93511813/169759534-84848b87-1421-4212-875b-0fce5c30b610.png)

Falls das so "gewollt" ist, kannst du das Ticket gerne auf Done setzen.

**Comment by FuratH** [comment]
Anpassung der Bilder folgt noch
